name: Provision EC2 and Configure Minecraft Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Initialize Terraform
        run: terraform init
        working-directory: minecraft-server-terraform-aws-instance

      - name: Apply Terraform (auto-approve)
        run: terraform apply -auto-approve
        working-directory: minecraft-server-terraform-aws-instance

      - name: Get EC2 Public IP
        run: |
          IP=$(terraform -chdir=minecraft-server-terraform-aws-instance output -raw minecraft_server_ip)
          echo "EC2_PUBLIC_IP=$IP" >> $GITHUB_ENV

      - name: Write SSH key to file
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: SSH into EC2 and start Minecraft
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ env.EC2_PUBLIC_IP }} << 'EOF'
            echo "Waiting 10s for instance readiness..."
            sleep 10
            sudo amazon-linux-extras install docker -y || sudo yum install -y docker
            sudo systemctl start docker
            sudo docker run -d -p 25565:25565 -e EULA=TRUE --name minecraft itzg/minecraft-server
          EOF
